board_real/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'board_real'
urlpatterns = [
        path('board_view/', views.boardview, name='board_view'),
        path('list/', views.index, name='index'),
        path('post/', views.post, name='post'),
        path('post/<int:post_id>/', views.detail, name='detail'),

        path('free/', views.FreeListView, name='free_list'), #자유
        path('qna/', views.QnaListView, name='qna_list'),  #수업 Q&A
        path('job/', views.JobListView, name='job_list'),  #취업 준비
        path('download/', views.download, name='download'),
        path('search/',views.search, name="search"), #글 검색
] 
#파일 추가를위한거 
# + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
#     import debug_toolbar
    urlpatterns += [
        # path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    # path('chat_list/', views.chat_list, name='chatList'),    
    # path('mychat_list/', views.mychat_list, name='mychatList'),   
    # path('chat_form/', views.chat_form, name='chatForm'),
    # path('chat_del/', views.chat_del, name='chatDelete'),
    # path('chat_list/<int:chat_id>/', views.chat_in, name='chatIn'),   
    # path('chat_out/', views.chat_out, name='chatOut'),
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    
]

member/urls.py
from django.urls import path
from . import views

app_name = 'member'
urlpatterns = [
        path('signup/', views.signup, name='signup'),
        path('login/', views.login, name='login'),
        path('logout/', views.logout, name='logout'),
        path('mypage/', views.mypage, name='mypage'),
        path('edit/', views.editUser, name='edit'),
        path('chat/', views.manageChat, name='chat'),
        path('delete/', views.deleteUser, name='delete'),
        path('randomnick/', views.randomNick, name='random'),
        path('more/board/', views.boardmore, name='board'),
        path('more/bbookmark/', views.bbookmarkmore, name='bbookmark'),
        path('more/reply/', views.replymore, name='reply'),
        path('more/rbookmark/', views.rbookmarkmore, name='rbookmark'),
]

board_real/models.py
from django.db import models
from django.db.models.fields import *
from member.models import User

# Create your models here.
class Category(models.Model):
    category_id = AutoField(primary_key = True)
    category_name = CharField(max_length = 15 ,null = False)

    class Meta:
        db_table = 'category'
        managed=True


class Board(models.Model):
    board_id = AutoField(primary_key=True, db_column='board_id')
    board_title = CharField(max_length=50, null = False, db_column='board_title')
    board_content = TextField(max_length = None, null = False, db_column='board_content' )
    board_reg_date = DateTimeField(auto_now_add=True, null = False, db_column='board_reg_date')
    board_mod_date = DateTimeField(auto_now=True, null = True, db_column='board_mod_date')
    board_deleted = CharField(max_length=1, default = 'N', db_column='board_deleted')
    board_like_cnt = PositiveIntegerField(default = 0, db_column='board_like_cnt')
    board_dis_cnt = PositiveIntegerField(default = 0, db_column='board_dis_cnt')
    temp_YN = CharField(max_length = 1, db_column='temp_YN')
    view_cnt = PositiveIntegerField(default = 0, db_column='view_cnt')
    user_like = models.ManyToManyField(User, related_name='like_relations')
    user_report = models.ManyToManyField(User, related_name='report_relations')
    
    #외래키
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, db_column='category_id')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null = True, db_column='user_id')
    #익명 으로 할거면 board에서 user를 다 지워야한다.
    # 에타같이 로그인이되도 각각의 사용자가 익명으로 작성이되는거 
    # 디씨같이 로그인이 되든안되든 게시글을 올릴떄 익명으로 작성이되는거 (user키를 뺴고 charfile로 board에 새로생성하면되죠?)

    class Meta:
        db_table = 'board'


class Reply(models.Model):
    reply_id=models.AutoField(primary_key=True,db_column='reply_id')
    reply_content=models.CharField(max_length=200,db_column='reply_content',null=False)
    reg_date=DateTimeField(auto_now=True,db_column='reg_date',null=False)
    mod_date=DateTimeField(auto_now=True,db_column='mod_date')
    reply_deleted=CharField(max_length=1, null=False, db_column='reply_deleted')
    reply_like_cnt=models.PositiveIntegerField(default=0, db_column='reply_like_cnt')
    reply_dis_cnt=models.PositiveIntegerField(default=0, db_column= 'reply_dis_cnt')
    #fk
    user=models.ForeignKey(User, on_delete=models.CASCADE, null = False, db_column='user_id', related_name='reply_user_relations')
    board=models.ForeignKey(Board, on_delete=models.CASCADE,null=False, db_column='board_id', related_name='reply_board_relations')

    class Meta:
        db_table = 'reply'

class File(models.Model):
    file_id=AutoField(primary_key=True,db_column='file_id')
    file_name=models.FileField(upload_to='uploads/',db_column='fine_name')
    file_reg_date=DateTimeField(auto_now_add=True,db_column='file_reg_date')
    file_mod_date=DateTimeField(auto_now=True,db_column='file_mod_date')
    file_deleted=CharField(max_length=1,default='N')
    #fk
    board=models.ForeignKey(Board, on_delete=models.CASCADE,null=False, db_column='board_id')

    class Meta:
        db_table = 'file'

class ReplyBookmark(models.Model):
    reg_date = DateTimeField(auto_now_add=True, db_column='reg_date')
    use_YN = CharField(max_length=1, null = False, default = 'Y')
    #fk
    user = models.ForeignKey(User,on_delete = models.CASCADE, null=False, db_column='user_id' )
    reply = models.ForeignKey(Reply, on_delete =models.CASCADE, null=False, db_column='reply_id')


    class Meta:
        db_table = 'reply_bookmark'

class BoardBookmark(models.Model):
    reg_date = DateTimeField(auto_now_add=True, db_column='reg_date')
    use_YN = CharField(max_length=1, null = False, default = 'Y')
    #fk
    user = models.ForeignKey(User,on_delete = models.CASCADE, null=False, db_column='user_id' )
    board = models.ForeignKey(Board, on_delete =models.CASCADE, null=False, db_column='board_id')

    class Meta:
        db_table = 'board_bookmark'

class ReplyLikeReport(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=False, db_column='reply_id')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, db_column='user_id')
    like_YN = models.CharField(max_length=1, null = False)

    class Meta:
        db_table = 'reply_like_report'

member/models.py
from django.db import models
from django.forms import CharField

# Create your models here.
# Create your models here.
class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    user_email = models.EmailField(verbose_name='사용자이메일', unique=True, max_length=50)
    user_pw = models.CharField(max_length=255, null=False)
    user_nick = models.CharField(max_length=30, unique=True)
    user_track = models.CharField(max_length=10, null=False)
    user_class = models.CharField(max_length=10, null=False)
    user_profile = models.CharField(max_length=255)
    
    # fk
    aivle = models.ForeignKey('Aivle', related_name='aivle', on_delete= models.CASCADE, db_column="aivle_id")
    
    class Meta:
        db_table = 'user'
        

class Aivle(models.Model):
    aivle_id = models.AutoField(primary_key = True)
    code = models.CharField(max_length= 8)
    
    class Meta:
        db_table = 'aivle'
        
class Adj(models.Model):
    adj_id = models.AutoField(primary_key=True)
    first = models.CharField(max_length=10, null=False)
    class Meta:
        db_table = 'adj'
            
class Noun(models.Model):
    noun_id = models.AutoField(primary_key = True)
    second = models.CharField(max_length=10, null=False)
    class Meta:
        db_table = 'noun'
    

member/views.py
from http.client import HTTPResponse
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, HttpResponse
from django.http import HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator
from .models import User, Aivle, Noun, Adj
from board_real.models import Board, Reply, BoardBookmark, ReplyBookmark
import random

# Create your views here.

def login(request):
    if request.method == 'POST':
        user_email = request.POST.get('email')
        user_pw = request.POST.get('password')
        try:
            m = User.objects.get(user_email=user_email, user_pw=user_pw)
        except User.DoesNotExist as e:
            return render(request, 'member/login.html')
        else:
            request.session['user_id'] = m.user_id
            request.session['user_email'] = m.user_email
            request.session['user_nick'] = m.user_nick
            request.session['user_profile'] = m.user_profile
            print(request.session.get('user_id'), request.session.get('user_nick'))
            return redirect('/')      
    else:
       return render(request, 'member/login.html')


def signup(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        code = request.POST.get('aivlecode')
        
        if password != password2:
            return redirect('member:signup')
        try:
            aivle = Aivle.objects.get(code = code)
            while True:
                adj = random.choice(Adj.objects.all())
                noun = random.choice(Noun.objects.all())
                nick = adj.first + ' ' + noun.second
                
                try: 
                    Aivle.objects.count(user_nick = nick)
                    continue;
                except:
                    break;
                
            m = User(
                user_email=email, 
                user_pw=password, 
                user_nick= nick, 
                user_track = '1',
                user_class = '1',
                aivle = aivle)
            m.save()
        except:
           return redirect('member:signup')
        return redirect('member:login')  
    
    else:
        return render(request, 'member/signup.html')

def logout(request):
    request.session.flush() # 전체 삭제
    return redirect('/')

def mypage(request):
    user_id = request.session.get('user_id', '0')
    
    if user_id == '0' :
        return redirect('member:login')
    else:
        user = User.objects.get(user_id = user_id)
        board_list = Board.objects.filter(user = user).filter(board_deleted='N').order_by('-board_id')[:5]
        reply = Reply.objects.filter(user=user).filter(reply_deleted='N').order_by('-reply_id')[:5]
        bbookmark = BoardBookmark.objects.filter(user=user).filter(use_YN = 'Y').order_by('-reg_date')[:5]
        rbookmark = ReplyBookmark.objects.filter(user=user).filter(use_YN='Y').order_by('-reg_date')[:5]
        return render(request, 'member/mypage.html', 
                      {'board_list':board_list,
                      'reply_list':reply,
                      'bbookmark_list':bbookmark,
                      'rbookmark_list':rbookmark})
    
def editUser(request):
    if request.method == 'POST':
        user_id = request.session.get('user_id', '0')
        
        if user_id == '0' :
            return redirect('member:login')
        else:
            user = User.objects.get(user_id = user_id)
            
            password = request.POST.get('password')
            if password == "" :
                nick = request.POST.get('nick')
                user.user_nick = nick
                user.save()
                request.session['user_nick'] = nick
                return redirect('member:mypage')
            password2 = request.POST.get('password2')
            if password != password2:
                return redirect('member:edit')
            user.user_pw = password
            nick = request.POST.get('nick')
            user.user_nick = nick
            user.save()
            request.session.flush()
            return redirect('member:login')
    else:
        user_id = request.session.get('user_id')
        user = User.objects.get(user_id = user_id)
        
        return render(request, 'member/edit.html',{'user':user})

def manageChat(request):
    return HttpResponse('미구현')

def deleteUser(request):
    if request.method == 'POST':
        password = request.POST.get('password')
        code = request.POST.get('aivlecode')
        user_id = request.session.get('user_id')
        
        try:
            user = User.objects.get(user_id = user_id)
            aivle = Aivle.objects.get(code = code)
        
            if user.user_pw == password and user.aivle == aivle :
                user.delete()
                request.session.flush() 
            
        except:
           return redirect('member:delete')
        return redirect('member:login')  
    
    else:
        return render(request, 'member/delete.html')

def randomNick(request):
    nick = ""
    while True:
        adj = random.choice(Adj.objects.all())
        noun = random.choice(Noun.objects.all())
        nick = adj.first + ' ' + noun.second
        
        try: 
            Aivle.objects.count(user_nick = nick)
            continue;
        except:
            break;
        
    return HttpResponse(nick)

def boardmore(request):
    user_id = request.session.get('user_id')
    user = User.objects.get(user_id = user_id)
    replys = Board.objects.all()
    replycnt = replys.count
    #페이징
    page = request.GET.get('page', '1')  # 페이지
    # 조회
    question_list = Board.objects.filter(user=user).order_by('-board_id')
    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj,'replycnt' : replycnt}
    return render(request, 'member/boardmore.html', context)

def bbookmarkmore(request):
    user_id = request.session.get('user_id')
    user = User.objects.get(user_id = user_id)
    replys = Board.objects.all()
    replycnt = replys.count
    question_list = []
    bbookmark = BoardBookmark.objects.filter(user=user).order_by('-board_id')
    #페이징
    page = request.GET.get('page', '1')  # 페이지
    # 조회
    question_list = Board.objects.prefetch_related('boardbookmark_set').filter(boardbookmark__user=user).filter(boardbookmark__use_YN='Y').order_by('-board_id')
    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj,'replycnt' : replycnt}
    return render(request, 'member/bbookmarkmore.html', context)

def replymore(request):
    user_id = request.session.get('user_id')
    user = User.objects.get(user_id = user_id)
    question_list = []
    #페이징
    page = request.GET.get('page', '1')  # 페이지
    # 조회
    question_list = Reply.objects.filter(user=user).order_by('-reply_id')
    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'member/replymore.html', context)

def rbookmarkmore(request):
    user_id = request.session.get('user_id')
    user = User.objects.get(user_id = user_id)
    question_list = []
    #페이징
    page = request.GET.get('page', '1')  # 페이지
    # 조회
    question_list = Reply.objects.prefetch_related('replybookmark_set').filter(replybookmark__user=user).filter(replybookmark__use_YN='Y').order_by('-reply_id')
    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'member/replymore.html', context)

member/templates/member/bbookmarkmore.html
<!DOCTYPE html>
{%  load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>테스트게시판</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/css/styles.css" rel="stylesheet" />
        <link href="/static/css/mypage.css" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- menu -->
            {% include 'menu.html' %}
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                {% include 'navbar.html' %}
                <!-- Page content-->
                <div class="container-fluid">
                    <!-- 여기서 UI 작업-->
                    <div style="width:1200px;margin-left:150px; margin-top:50px;">
                        <table class="table">
                            <thead class="thead-light">
                                <tr class="text-center">
                                    <th scope="col">번호</th>
                                    <th scope="col">제목</th>
                                    <th scope="col">작성자</th>
                                    <th scope="col">작성일</th>
                                    <th scope="col">조회</th>
                                    <th scope="col">좋아요</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for board in question_list %}
                                <tr class="text-center">
                                    {% comment %} 글 번호 {% endcomment %}
                                    <th scope="row">
                                        {% if board.view_cnt > 20 %}
                                            <span>🔥&nbsp&nbsp</span>
                                        {% else %}
                                            <span>&nbsp&nbsp&nbsp&nbsp&nbsp<span>
                                        {% endif %}
                                        <span>
                                            {{ board.board_id }}
                                        </span>
                                        <span>
                                        </span>
                                        <span>
                                            {% if board.file_set.count %}
                                                <span>📁</span>
                                            {% else %}
                                                <span>&nbsp&nbsp&nbsp&nbsp&nbsp<span>
                                            {% endif %}
                                        </span>
                                
                                    </th>
                                    
                                    {% comment %} 글 제목 {% endcomment %}
                                    <td>
                                        <a class = "mp-link" href={% url "board_real:board_view" %}?id={{board.board_id}}>
                                            <span>{{ board.board_title }} 
                                                {% if board.reply_set.count %}
                                                <span>[{{ board.reply_set.count }}]</span>
                                                {% endif %}
                                            </span>
                                        </a>
                                    </td>
                                    {% comment %} 작성자 닉네임 {% endcomment %}
                                    <td><span>{{ board.user.user_nick }}</span></td>
                                    {% comment %} 작성 시간 {% endcomment %}
                                    <td>
                                        <span>{{ board.board_reg_date | date:"Y-m-d h:i" }}</span>
                                    </td>
                                    {% comment %} 조회수 {% endcomment %}
                                    <td><span>{{ board.view_cnt }}</span></td>
                                    {% comment %} 좋아요 수 {% endcomment %}
                                    <td><span>{{ board.board_like_cnt }}</span></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>


                        <!-- 페이징처리 시작 -->
                        <ul class="pagination justify-content-center">
                            <!-- 이전페이지 -->
                            {% if question_list.has_previous %}
                            <a class="page-link"  style="color:black;" href="?page=1">처음</a>
                            <li class="page-item">
                                <a class="page-link" style="color:black;"href="?page={{ question_list.previous_page_number }}">◀</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" style="color:black;" tabindex="-1" aria-disabled="true" href="#">◀</a>
                            </li>
                            {% endif %}
                            <!-- 페이지리스트 -->
                            {% for page_number in question_list.paginator.page_range %}
                            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                                {% if page_number == question_list.number %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" style="color:black;" href="?page={{ page_number }}">{{ page_number }}</a>
                                </li>
                                {% else %}
                                <li class="page-item">
                                    <a class="page-link" style="color:black;" href="?page={{ page_number }}">{{ page_number }}</a>
                                </li>
                                {% endif %}
                            {% endif %}
                            {% endfor %}
                            <!-- 다음페이지 -->
                            {% if question_list.has_next %}
                            <li class="page-item">
                                <a class="page-link" style="color:black;" href="?page={{ question_list.next_page_number }}">▶</a>
                            </li>
                            <a class="page-link" style="color:black;" href="?page={{ question_list.paginator.num_pages }}">끝</a>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" style="color:black;" tabindex="-1" aria-disabled="true" href="#">▶</a>
                            </li>
                            {% endif %}
                        </ul>
                        <!-- 페이징처리 끝 -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/js/scripts.js"></script>
    </body>
</html>

member/templates/member/boardmore.html
<!DOCTYPE html>
{%  load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>테스트게시판</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/css/styles.css" rel="stylesheet" />
        <link href="/static/css/mypage.css" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- menu -->
            {% include 'menu.html' %}
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                {% include 'navbar.html' %}
                <!-- Page content-->
                <div class="container-fluid">
                    <!-- 여기서 UI 작업-->
                    <div style="width:1710px;margin-left:150px;margin-top:50px;">
                        <table class="table">
                            <thead class="thead-light">
                                <tr class="text-center">
                                    <th scope="col">번호</th>
                                    <th scope="col">제목</th>
                                    <th scope="col">작성자</th>
                                    <th scope="col">작성일</th>
                                    <th scope="col">조회</th>
                                    <th scope="col">좋아요</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for board in question_list %}
                                <tr class="text-center">
                                    {% comment %} 글 번호 {% endcomment %}
                                    <th scope="row">
                                        {% if board.view_cnt > 20 %}
                                            <span>🔥&nbsp&nbsp</span>
                                        {% else %}
                                            <span>&nbsp&nbsp&nbsp&nbsp&nbsp<span>
                                        {% endif %}
                                        <span>
                                            {{ board.board_id }}
                                        </span>
                                        <span>
                                        </span>
                                        <span>
                                            {% if board.file_set.count %}
                                                <span>📁</span>
                                            {% else %}
                                                <span>&nbsp&nbsp&nbsp&nbsp&nbsp<span>
                                            {% endif %}
                                        </span>
                                
                                    </th>
                                    
                                    {% comment %} 글 제목 {% endcomment %}
                                    <td>
                                        <a class = "mp-link" href= {% url "board_real:board_view" %}?id={{board.board_id}}>
                                            <span>{{ board.board_title }} 
                                                {% if board.reply_set.count %}
                                                <span>[{{ board.reply_set.count }}]</span>
                                                {% endif %}
                                            </span>
                                        </a>
                                    </td>
                                    {% comment %} 작성자 닉네임 {% endcomment %}
                                    <td><span>{{ board.user.user_nick }}</span></td>
                                    {% comment %} 작성 시간 {% endcomment %}
                                    <td>
                                        <span>{{ board.board_reg_date | date:"Y-m-d h:i" }}</span>
                                    </td>
                                    {% comment %} 조회수 {% endcomment %}
                                    <td><span>{{ board.view_cnt }}</span></td>
                                    {% comment %} 좋아요 수 {% endcomment %}
                                    <td><span>{{ board.board_like_cnt }}</span></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>


                        <!-- 페이징처리 시작 -->
                        <ul class="pagination justify-content-center">
                            <!-- 이전페이지 -->
                            {% if question_list.has_previous %}
                            <a class="page-link"  style="color:black;" href="?page=1">처음</a>
                            <li class="page-item">
                                <a class="page-link" style="color:black;"href="?page={{ question_list.previous_page_number }}">◀</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" style="color:black;" tabindex="-1" aria-disabled="true" href="#">◀</a>
                            </li>
                            {% endif %}
                            <!-- 페이지리스트 -->
                            {% for page_number in question_list.paginator.page_range %}
                            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                                {% if page_number == question_list.number %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" style="color:black;" href="?page={{ page_number }}">{{ page_number }}</a>
                                </li>
                                {% else %}
                                <li class="page-item">
                                    <a class="page-link" style="color:black;" href="?page={{ page_number }}">{{ page_number }}</a>
                                </li>
                                {% endif %}
                            {% endif %}
                            {% endfor %}
                            <!-- 다음페이지 -->
                            {% if question_list.has_next %}
                            <li class="page-item">
                                <a class="page-link" style="color:black;" href="?page={{ question_list.next_page_number }}">▶</a>
                            </li>
                            <a class="page-link" style="color:black;" href="?page={{ question_list.paginator.num_pages }}">끝</a>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" style="color:black;" tabindex="-1" aria-disabled="true" href="#">▶</a>
                            </li>
                            {% endif %}
                        </ul>
                        <!-- 페이징처리 끝 -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/js/scripts.js"></script>
    </body>
</html>