chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    # path('chat_list/', views.chat_list, name='chatList'),    
    # path('mychat_list/', views.mychat_list, name='mychatList'),   
    # path('chat_form/', views.chat_form, name='chatForm'),
    # path('chat_del/', views.chat_del, name='chatDelete'),
    # path('chat_list/<int:chat_id>/', views.chat_in, name='chatIn'),   
    # path('chat_out/', views.chat_out, name='chatOut'),
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    
]

member/urls.py
from django.urls import path
from . import views

app_name = 'member'
urlpatterns = [
        path('signup/', views.signup, name='signup'),
        path('login/', views.login, name='login'),
        path('logout/', views.logout, name='logout'),
        path('mypage/', views.mypage, name='mypage'),
        path('edit/', views.editUser, name='edit'),
        path('chat/', views.manageChat, name='chat'),
        path('delete/', views.deleteUser, name='delete'),
        path('randomnick/', views.randomNick, name='random'),
        path('more/board/', views.boardmore, name='board'),
        path('more/bbookmark/', views.bbookmarkmore, name='bbookmark'),
        path('more/reply/', views.replymore, name='reply'),
        path('more/rbookmark/', views.rbookmarkmore, name='rbookmark'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

# Create your views here.

def main(request):
    return render(request, 'main/index.html', {
    })

main/templates/main/index.html
<!DOCTYPE html>
{%  load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Kvely 케블리</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- menu -->
            {% include 'menu.html' %}
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                {% include 'navbar.html' %}
                <!-- Page content-->
                <div class="container-fluid">
                        <iframe width="1280" height="720" src="https://www.youtube.com/embed/G6WzCKSVI9I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </p>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/js/scripts.js"></script>
    </body>
</html>

main/templates/main/menu.html
<!-- menu bar -->
<div class="border-end bg-white" id="sidebar-wrapper">
    <div class="sidebar-heading border-bottom bg-light" style ="text-align: center; " >
        <p style ="color: #23BDB7; font-weight: bold " >Kvely</p>
    </div>
    <div class="list-group list-group-flush">
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/board_real/list">게시판</a>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href={% url "chat:index" %}>채팅</a>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href={% url "member:mypage" %}>마이페이지</a>

    </div>
</div>

main/templates/main/navbar.html
<!-- nav bar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <!-- 메뉴 토글 버튼 -->
        <button type="button" id="sidebarToggle" style="border: 0;">
            <span class="navbar-toggler-icon"></span>
        </button>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                <li class="nav-item active"><a class="nav-link" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="/">Link</a></li>
                {% if request.session.user_id %}
                <!--로그인 했을때-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.session.user_nick }} 님</a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href= {% url "member:mypage" %}>마이페이지</a>
                        <a class="dropdown-item" href="/member/more/bbookmark">북마크</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href={% url "member:logout" %}>로그아웃</a>
                    </div>
                </li>
                <!--로그인 안 했을 때-->
                {% else %}
                <li class="nav-item active"><a class="nav-link" href={% url "member:login" %}>로그인</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>