board_real/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'board_real'
urlpatterns = [
        path('board_view/', views.boardview, name='board_view'),
        path('list/', views.index, name='index'),
        path('post/', views.post, name='post'),
        path('post/<int:post_id>/', views.detail, name='detail'),

        path('free/', views.FreeListView, name='free_list'), #자유
        path('qna/', views.QnaListView, name='qna_list'),  #수업 Q&A
        path('job/', views.JobListView, name='job_list'),  #취업 준비
        path('download/', views.download, name='download'),
        path('search/',views.search, name="search"), #글 검색
] 
#파일 추가를위한거 
# + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
#     import debug_toolbar
    urlpatterns += [
        # path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    # path('chat_list/', views.chat_list, name='chatList'),    
    # path('mychat_list/', views.mychat_list, name='mychatList'),   
    # path('chat_form/', views.chat_form, name='chatForm'),
    # path('chat_del/', views.chat_del, name='chatDelete'),
    # path('chat_list/<int:chat_id>/', views.chat_in, name='chatIn'),   
    # path('chat_out/', views.chat_out, name='chatOut'),
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    
]

board_real/models.py
from django.db import models
from django.db.models.fields import *
from member.models import User

# Create your models here.
class Category(models.Model):
    category_id = AutoField(primary_key = True)
    category_name = CharField(max_length = 15 ,null = False)

    class Meta:
        db_table = 'category'
        managed=True


class Board(models.Model):
    board_id = AutoField(primary_key=True, db_column='board_id')
    board_title = CharField(max_length=50, null = False, db_column='board_title')
    board_content = TextField(max_length = None, null = False, db_column='board_content' )
    board_reg_date = DateTimeField(auto_now_add=True, null = False, db_column='board_reg_date')
    board_mod_date = DateTimeField(auto_now=True, null = True, db_column='board_mod_date')
    board_deleted = CharField(max_length=1, default = 'N', db_column='board_deleted')
    board_like_cnt = PositiveIntegerField(default = 0, db_column='board_like_cnt')
    board_dis_cnt = PositiveIntegerField(default = 0, db_column='board_dis_cnt')
    temp_YN = CharField(max_length = 1, db_column='temp_YN')
    view_cnt = PositiveIntegerField(default = 0, db_column='view_cnt')
    user_like = models.ManyToManyField(User, related_name='like_relations')
    user_report = models.ManyToManyField(User, related_name='report_relations')
    
    #외래키
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, db_column='category_id')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null = True, db_column='user_id')
    #익명 으로 할거면 board에서 user를 다 지워야한다.
    # 에타같이 로그인이되도 각각의 사용자가 익명으로 작성이되는거 
    # 디씨같이 로그인이 되든안되든 게시글을 올릴떄 익명으로 작성이되는거 (user키를 뺴고 charfile로 board에 새로생성하면되죠?)

    class Meta:
        db_table = 'board'


class Reply(models.Model):
    reply_id=models.AutoField(primary_key=True,db_column='reply_id')
    reply_content=models.CharField(max_length=200,db_column='reply_content',null=False)
    reg_date=DateTimeField(auto_now=True,db_column='reg_date',null=False)
    mod_date=DateTimeField(auto_now=True,db_column='mod_date')
    reply_deleted=CharField(max_length=1, null=False, db_column='reply_deleted')
    reply_like_cnt=models.PositiveIntegerField(default=0, db_column='reply_like_cnt')
    reply_dis_cnt=models.PositiveIntegerField(default=0, db_column= 'reply_dis_cnt')
    #fk
    user=models.ForeignKey(User, on_delete=models.CASCADE, null = False, db_column='user_id', related_name='reply_user_relations')
    board=models.ForeignKey(Board, on_delete=models.CASCADE,null=False, db_column='board_id', related_name='reply_board_relations')

    class Meta:
        db_table = 'reply'

class File(models.Model):
    file_id=AutoField(primary_key=True,db_column='file_id')
    file_name=models.FileField(upload_to='uploads/',db_column='fine_name')
    file_reg_date=DateTimeField(auto_now_add=True,db_column='file_reg_date')
    file_mod_date=DateTimeField(auto_now=True,db_column='file_mod_date')
    file_deleted=CharField(max_length=1,default='N')
    #fk
    board=models.ForeignKey(Board, on_delete=models.CASCADE,null=False, db_column='board_id')

    class Meta:
        db_table = 'file'

class ReplyBookmark(models.Model):
    reg_date = DateTimeField(auto_now_add=True, db_column='reg_date')
    use_YN = CharField(max_length=1, null = False, default = 'Y')
    #fk
    user = models.ForeignKey(User,on_delete = models.CASCADE, null=False, db_column='user_id' )
    reply = models.ForeignKey(Reply, on_delete =models.CASCADE, null=False, db_column='reply_id')


    class Meta:
        db_table = 'reply_bookmark'

class BoardBookmark(models.Model):
    reg_date = DateTimeField(auto_now_add=True, db_column='reg_date')
    use_YN = CharField(max_length=1, null = False, default = 'Y')
    #fk
    user = models.ForeignKey(User,on_delete = models.CASCADE, null=False, db_column='user_id' )
    board = models.ForeignKey(Board, on_delete =models.CASCADE, null=False, db_column='board_id')

    class Meta:
        db_table = 'board_bookmark'

class ReplyLikeReport(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=False, db_column='reply_id')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, db_column='user_id')
    like_YN = models.CharField(max_length=1, null = False)

    class Meta:
        db_table = 'reply_like_report'

board_real/forms.py
from django import forms
from .models import File,Board
from .models import File

class ReportLikeForm(forms.Form):
    board_id = forms.IntegerField(max_value=None)
    reply_id = forms.IntegerField(max_value=None)
    user_id = forms.IntegerField(max_value=None)
    report_flag = forms.CharField(max_length=1)

class DeleteBoardForm(forms.Form):
    delete_YN = forms.CharField(max_length=1, required=False)
    id = forms.IntegerField(max_value=None)
    board_id = forms.IntegerField(max_value = None)

class ReplyForm(forms.Form):
    board_id = forms.IntegerField(max_value=None)
    user_id = forms.IntegerField(max_value=None)
    reply_content = forms.CharField(max_length=1500, required=True)

board_real/views.py
from distutils.command.upload import upload
from unicodedata import category
from unicodedata import name
from django.http import HttpResponseNotFound, HttpResponseRedirect, Http404, response
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from .forms import * 
from .models import *
from django.db import transaction
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from .models import Board,User
def index(request):

    replys = Reply.objects.filter(reply_deleted='N')
    replycnt = replys.count()
    
    #페이징
    page = request.GET.get('page', '1')  # 페이지
    # 조회
    question_list = Board.objects.filter(board_deleted='N').order_by('-board_reg_date')
    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj,'replycnt' : replycnt}
    return render(request, 'board_real/list.html', context)


# @login_required
@transaction.atomic
def post(request):
    try:
        if request.method == "POST":
            board_title = request.POST['board_title']
            board_content = request.POST['board_content']
            category_name = request.POST['category_name']
            category = Category.objects.get(category_name=category_name)
            user_id=request.session.get('user_id')
            user = User.objects.get(pk=user_id)
            board = Board(
                board_title=board_title, 
                board_content=board_content, board_reg_date = timezone.now(),
                category=category, user=user )
            board.save()
            # 파일업로드 
            myfile=request.FILES.get('myfile')
            if myfile:
                fs = FileSystemStorage() # 실제 파일이 저장되고
                file = File(file_name='uploads/'+myfile.name, board=board) # db에 저장
                file.save()
                filename = fs.save('uploads/'+myfile.name, myfile)
                uploaded_file_url = fs.url(filename)
            return redirect('board_real:index')
        else:
            return render(request, 'board_real/post.html')
    except:
        return HttpResponseNotFound(content='404 NOT FOUND')


import os
def boardview(request):
    #form 처리
    if request.method == 'POST':
        if 'report_flag' in request.POST:
            form = ReportLikeForm(request.POST)
            cboard = Board.objects.get(board_id = form.data['board_id'])
            cuser = User.objects.get(user_id = form.data['user_id'])
            if form.data['reply_id'] != '-1':
                creply = creply = Reply.objects.get(reply_id = form.data['reply_id'])
            if form.data['report_flag'] == 'l':
                if form.data['reply_id'] != '-1':
                    ReplyLikeReport.objects.create(reply = creply, user=cuser, like_YN = 'Y')
                    creply.reply_like_cnt += 1
                    creply.save()
                    return redirect('/board_real/board_view?id='+form.data['board_id'])
                cboard.user_like.add(cuser)
                cboard.board_like_cnt += 1
                cboard.save()
                return redirect('/board_real/board_view?id='+form.data['board_id'])
            if form.data['report_flag'] == 'r':
                if form.data['reply_id'] != '-1':
                    ReplyLikeReport.objects.create(reply = creply, user=cuser, like_YN = 'N')
                    creply.reply_dis_cnt += 1
                    creply.save()
                    return redirect('/board_real/board_view?id='+form.data['board_id'])
                cboard.user_report.add(cuser)
                cboard.board_dis_cnt += 1
                cboard.save()
                return redirect('/board_real/board_view?id='+form.data['board_id'])
            if form.data['report_flag'] == 'b':
                if form.data['reply_id'] != '-1':
                    replymark, rflag = ReplyBookmark.objects.get_or_create(reply = creply, user = cuser)
                    if not rflag:
                        replymark.use_YN = 'Y'
                        replymark.save()
                    return redirect('/board_real/board_view?id='+form.data['board_id'])
                boardmark,bflag = BoardBookmark.objects.get_or_create(board = cboard, user = cuser)
                if not bflag:
                    boardmark.use_YN = 'Y'
                    boardmark.save()
                return redirect('/board_real/board_view?id='+form.data['board_id'])
            if form.data['report_flag'] == 'c':
                if form.data['reply_id'] != '-1':
                    Rreply = ReplyBookmark.objects.get(reply = creply)
                    Rreply.use_YN = 'N'
                    Rreply.save()
                    return redirect('/board_real/board_view?id='+form.data['board_id'])
                Bboard = BoardBookmark.objects.get(board = cboard, user = cuser)
                Bboard.use_YN = 'N'
                Bboard.save()
                return redirect('/board_real/board_view?id='+form.data['board_id'])
            return HttpResponse('reportflag detected')
        if 'delete_YN' in request.POST:
            form = DeleteBoardForm(request.POST)
            b_id = form.data['id']
            if form.data['delete_YN'] == 'Y':
                b = Board.objects.get(board_id = b_id)
                b.board_deleted = 'Y'
                b.save()
                return redirect('/board_real/list')
            else:
                b = Reply.objects.get(reply_id = b_id)
                b.reply_deleted='Y'
                b.save()
                return redirect('/board_real/board_view?id='+form.data['board_id'])
        else:
            form = ReplyForm(request.POST)
            if form.is_valid():
                content = form.cleaned_data['reply_content']
                uid = form.data['user_id']
                bid = form.data['board_id']
                Reply.objects.create(reply_content=content, reply_deleted = 'N', user_id = uid, board_id = bid)
                return redirect('/board_real/board_view?id='+form.data['board_id'])
            else:
                return redirect('/board_real/board_view?id='+form.data['board_id'])
    
    reqId = request.GET.get('id')
    
    try:
        board= Board.objects.get(board_id=reqId)
    except:
        #return HttpResponse('<h1>요청하신 페이지를 찾을 수 없습니다</h2>')
        return HttpResponseNotFound(content='404 NOT FOUND')
    if board.board_deleted == 'Y':
        return HttpResponseNotFound(content='404 NOT FOUND')
    replys = Reply.objects.filter(board_id = reqId, reply_deleted='N')
    category = board.category.category_name
    user = User.objects.get(user_id = board.user.user_id)
    replycnt = replys.count
    formlike = ReportLikeForm()
    formdelete = DeleteBoardForm()
    formreply = ReplyForm()

    try:
        boardBookmarked = BoardBookmark.objects.filter(board_id = board.board_id, use_YN = 'Y')
    except:
        boardBookmarked = None
    try:
        replyBookmarked = ReplyBookmark.objects.filter( reply__in = replys, use_YN = 'Y')
    except:
        replyBookmarked = None
    try:
        replyLike = ReplyLikeReport.objects.filter(reply__in = replys, like_YN = 'Y')
    except:
        replyLike = None
    try:
        replyReport = ReplyLikeReport.objects.filter(reply__in = replys, like_YN = 'N')
    except:
        replyReport = None
    board.view_cnt += 1
    board.save()
    return render(request, 'board_real/board_view.html',
    {'board':board, 'replys':replys,
    'category':category, 'user':user, 'replycnt':replycnt,
    'formlike':formlike, 'formdelete':formdelete, 'boardBookmarked':boardBookmarked,
    'formreply':formreply, 'replyBookmarked':replyBookmarked, 'replyLike':replyLike, 'replyReport':replyReport
     })
    

def detail(request, post_id):
    try:
        board = Board.objects.get(pk=post_id)
    except Board.DoesNotExist:
        raise Http404("Does not exist!")
    return render(request, 'board_real/detail.html', {'board': board})



def FreeListView(request):
    # free_list=Board.objects.filter(category_id=2).order_by('-board_reg_date')
    # context = {'free_list': free_list}
    # return render(request, 'board_real/free_list.html', context)

    page = request.GET.get('page', '1')
    free_list = Board.objects.filter(category_id=2).order_by('-board_reg_date')
    paginator = Paginator(free_list, 10)
    page_obj = paginator.get_page(page)
    context = {'free_list': page_obj}
    return render(request, 'board_real/free_list.html', context)

def QnaListView(request):
    # qna_list=Board.objects.filter(category_id=3).order_by('-board_reg_date')
    # context2 = {'qna_list': qna_list}
    # return render(request, 'board_real/qna_list.html', context2)

    page = request.GET.get('page', '1')
    qna_list = Board.objects.filter(category_id=3).order_by('-board_reg_date')
    paginator = Paginator(qna_list, 10)
    page_obj = paginator.get_page(page)
    context = {'qna_list': page_obj}
    return render(request, 'board_real/qna_list.html', context)

def JobListView(request):
    # job_list=Board.objects.filter(category_id=4).order_by('-board_reg_date')
    # context3 = {'job_list': job_list}
    # return render(request, 'board_real/job_list.html', context3)

    page = request.GET.get('page', '1')
    job_list = Board.objects.filter(category_id=4).order_by('-board_reg_date')
    paginator = Paginator(job_list, 10)
    page_obj = paginator.get_page(page)
    context = {'job_list': page_obj}
    return render(request, 'board_real/job_list.html', context)

def download(request):
    id = request.GET.get('id')
    board = Board.objects.get(pk=id)

board_real/templates/board_real/list.html
<!DOCTYPE html>
{%  load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>전체 게시판</title>
        <style>
            span{color:black}
            a{font-size:18px;}
            #board_title:hover{color:#23BDB7;}
        </style>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/css/styles.css" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- menu -->
            {% include 'menu.html' %}
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                {% include 'navbar.html' %}
                <!-- Page content-->
                <div class="container-fluid">
                <!-- 여기서 UI 작업-->
                <div style="font-size:40px;font-weight: 800; color:rgb(76, 76, 76); margin-left:150px;">
                    AIVLE 게시판
                </div>
                    <!-- 카테고리 시작 -->
                    <header>
                        <div style="margin-top: 30px;">
                            <div style="display: inline-block;width:130px;height: 60px; border:none;margin-right:50px;margin-left:150px;" >
                                <a style=" text-decoration: underline; text-underline-position:under; color:#23BDB7;font-size: 25px; font-weight: 800;"href='http://127.0.0.1:8000/board_real/list'>전체</a>
                            </div> 
                            <div style="display: inline-block;width:130px;height: 60px; border:none;margin-right:50px;" >
                                <a style=" color:rgb(122, 115, 115);font-size: 25px; font-weight: 800;"href='http://127.0.0.1:8000/board_real/free'>자유</a>
                            </div> 
                            <div style="display: inline-block;width:130px;height: 60px; border:none;margin-right:50px;" >
                                <a style=" color:rgb(122, 115, 115);font-size: 25px; font-weight: 800;"href='http://127.0.0.1:8000/board_real/qna'>수업 QnA</a>
                            </div> 

                            <div style="display: inline-block;width:130px;height: 60px; border:none;margin-right:50px;" >
                                <a style=" color:rgb(122, 115, 115);font-size: 25px; font-weight: 800;"href='http://127.0.0.1:8000/board_real/job'>취업 준비</a>
                            </div> 
                        </div>
                        {% comment %} 글 검색 부분 {% endcomment %}
                        <form method="GET" action="{% url 'board_real:search' %}">
                            <div id="search">
                              <input placeholder="  검색어를 입력하세요" name="search" type="text"style="border:5px solid #23BDB7;background-color:white; padding:10px; color:rgb(76, 76, 76); font-size:25px;border-radius: 30px;
                              width:1110px; height: 50px; margin-left:460px; margin-top:20px; margin-bottom:50px;">
                              <button class="btn btn-primary" type="submit"style="position:absolute;border:none;background-color:#23BDB7; padding:10px; color:white; font-size:25px;border-radius: 0px 30px 30px 0px;
                              width:200px; height: 50px; left:1628px; top:230px; ">
                                검색</button>
                            </div>
                        </form>

                    </header>
                    <!-- 카테고리 끝 -->

                    <!-- 게시판 리스트 시작 -->
                    <div style="width:1710px;margin-left:150px">
                        <table class="table">
                            <thead class="thead-light">
                                <tr class="text-center">
                                    <th scope="col">번호</th>
                                    <th scope="col">제목</th>
                                    <th scope="col">작성자</th>
                                    <th scope="col">작성일</th>
                                    <th scope="col">조회</th>
                                    <th scope="col">좋아요</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for board in question_list %}
                                <tr class="text-center">
                                    {% comment %} 글 번호 {% endcomment %}
                                    <th scope="row">
                                        {% if board.view_cnt > 20 %}
                                            <span>🔥&nbsp&nbsp</span>
                                        {% else %}
                                            <span>&nbsp&nbsp&nbsp&nbsp&nbsp<span>
                                        {% endif %}
                                        <span>
                                            {{ board.board_id }}
                                        </span>
                                        <span>
                                        </span>
                                        <span>
                                            {% if board.file_set.count %}
                                                <span>📁</span>
                                            {% else %}
                                                <span>&nbsp&nbsp&nbsp&nbsp&nbsp<span>
                                            {% endif %}
                                        </span>
                                
                                    </th>
                                    
                                    {% comment %} 글 제목 {% endcomment %}
                                    <td>
                                        <a href={% url "board_real:board_view" %}?id={{board.board_id}}>
                                            <span id="board_title">{{ board.board_title }} 
                                                {% if board.reply_board_relations.count %}
                                                <span>[{{ board.reply_board_relations.count}}]</span>
                                                {% endif %}
                                            </span>
                                        </a>
                                    </td>
                                    {% comment %} 작성자 닉네임 {% endcomment %}
                                    <td><span>{{ board.user.user_nick }}</span></td>
                                    {% comment %} 작성 시간 {% endcomment %}
                                    <td>
                                        <span>{{ board.board_reg_date | date:"Y-m-d h:i" }}</span>
                                    </td>
                                    {% comment %} 조회수 {% endcomment %}
                                    <td><span>{{ board.view_cnt }}</span></td>
                                    {% comment %} 좋아요 수 {% endcomment %}
                                    <td><span>{{ board.board_like_cnt }}</span></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>


                        <!-- 페이징처리 시작 -->
                        <ul class="pagination justify-content-center">
                            <!-- 이전페이지 -->
                            {% if question_list.has_previous %}
                            <a class="page-link"  style="color:black;" href="?page=1">처음</a>
                            <li class="page-item">
                                <a class="page-link" style="color:black;"href="?page={{ question_list.previous_page_number }}">◀</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" style="color:black;" tabindex="-1" aria-disabled="true" href="#">◀</a>
                            </li>
                            {% endif %}
                            <!-- 페이지리스트 -->
                            {% for page_number in question_list.paginator.page_range %}
                            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                                {% if page_number == question_list.number %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" style="color:black;" href="?page={{ page_number }}">{{ page_number }}</a>
                                </li>
                                {% else %}
                                <li class="page-item">
                                    <a class="page-link" style="color:black;" href="?page={{ page_number }}">{{ page_number }}</a>
                                </li>
                                {% endif %}
                            {% endif %}
                            {% endfor %}
                            <!-- 다음페이지 -->
                            {% if question_list.has_next %}
                            <li class="page-item">
                                <a class="page-link" style="color:black;" href="?page={{ question_list.next_page_number }}">▶</a>
                            </li>
                            <a class="page-link" style="color:black;" href="?page={{ question_list.paginator.num_pages }}">끝</a>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" style="color:black;" tabindex="-1" aria-disabled="true" href="#">▶</a>
                            </li>
                            {% endif %}
                        </ul>
                        <!-- 페이징처리 끝 -->

                        <!-- 글 작성 버튼 -->
                        <div class="row">
                            <div class="col-auto mr-auto"></div>
                            <div class="col-auto">
                                <button type="button" class="btn btn-primary btn-lg" 
                                style="width:130px; height: 60px;background-color:#23BDB7 !important; border:none;" 
                                onclick="location.href='http://127.0.0.1:8000/board_real/post/'">글 작성</button>
                            </div>
                        </div>
                        <!-- 글 작성 버튼 끝 -->
                    </div>
                    <!-- 게시판 리스트 끝 -->

                </div>
            </div>
        </div>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/static/js/scripts.js"></script>
    </body>
</html>

board_real/templates/board_real/post.html
<!DOCTYPE html>
{%  load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>테스트게시판</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- menu -->
            {% include 'menu.html' %}
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                {% include 'navbar.html' %}
                <!-- Page content-->
                <div class="container-fluid">
                    {% load static %}
<!--게시판 글쓰기-->



    <form action="{% url 'board_real:post' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <legend>게시판 글쓰기</legend>
    <!--제목 -->
            <div class="form-group row">
            <label for="inputTitle" class="col-sm-2 col-form-label"><strong>제목</strong></label>
            <div class="col-sm-10">
                <input type="text" name="board_title" class="form-control" id="inputTitle" value ='{{board.board_title}}'>
            </div>
        </div>
<!--카테고리 -->
    <div class="form-group">
      <label for="exampleSelect1" class="form-label mt-4">카테고리</label>
      <select class="form-select" id="exampleSelect1" name='category_name'>
        <option>전체</option>
        <option>자유</option>
        <option>수업 Q&A</option>
        <option>취업준비</option>
      </select>
    </div>
  
    <!--글작성 부분-->
    <div class="form-group">
      <label for="exampleTextarea" class="form-label mt-4">글작성</label>
      <textarea type="text" name="board_content" class="form-control" id="inputContent" rows="10"> </textarea>

    </div>

    <!--파일업로드-->
    <div class="form-group">
      <label for="formFile" class="form-label mt-4">파일업로드</label>
      <input class="form-control" type="file" id="file" name='myfile'>
      {% comment %} <input type="submit" value="전송"> {% endcomment %}
    </div>
  
    <br>
    <input type='hidden' value='{{board.board_id}}' name = 'board_id'/>
    <button type ="button" class = "btn btn-primary" style = "float:left;" onclick = "location.href ='/board_real/list'">돌아가기</button>
    <input class="btn btn-primary" type="submit" style = "float:right;" role="button" value="글쓰기">  
                      </form>    

                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/js/scripts.js"></script>
    </body>
</html>